version: '3.8'
services:
  api:
    build: .
    container_name: mlops-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_LOCAL_PATH=/app/models/model.joblib
    depends_on:
      - mlflow
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow.db
      --default-artifact-root /mlflow
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow
      - ./mlflow.db:/mlflow.db
    restart: unless-stopped

volumes:
  mlflow_artifacts:
